package com.mango.zombies.entities;

import com.mango.zombies.serializers.ConfigEntityJsonSerializer;

public class ConfigEntity {

	public static final String AUTO_GENERATE_DEFAULT_PERKS_JSON_TAG = "auto_generate_default_perks";
	public static final String AUTO_GENERATE_DEFAULT_WEAPON_CLASSES_JSON_TAG = "auto_generate_default_weapon_classes";
	public static final String AUTO_GENERATE_DEFAULT_WEAPONS_JSON_TAG = "auto_generate_default_weapons";
	public static final String DEFAULT_MYSTERY_BOX_COST_JSON_TAG = "default_mystery_box_cost";
	public static final ConfigEntityJsonSerializer SERIALIZER = new ConfigEntityJsonSerializer();
	public static final String WORLD_NAME_JSON_TAG = "world_name";

	private boolean autoGenerateDefaultPerks = true;
	private boolean autoGenerateDefaultWeaponClasses = true;
	private boolean autoGenerateDefaultWeapons = true;
	private int defaultMysteryBoxCost = 950;
	private String worldName;

	/**
	 * Gets whether default perks should be generated automatically.
	 */
	public boolean isAutoGenerateDefaultPerks() {
		return autoGenerateDefaultPerks;
	}

	/**
	 * Sets whether default perks should be generated automatically.
	 */
	public void setAutoGenerateDefaultPerks(boolean autoGenerateDefaultPerks) {
		this.autoGenerateDefaultPerks = autoGenerateDefaultPerks;
	}

	/**
	 * Gets whether default weapon classes should be generated automatically.
	 */
	public boolean isAutoGenerateDefaultWeaponClasses() {
		return autoGenerateDefaultWeaponClasses;
	}

	/**
	 * Sets whether default weapon classes should be generated automatically.
	 */
	public void setAutoGenerateDefaultWeaponClasses(boolean autoGenerateDefaultWeaponClasses) {
		this.autoGenerateDefaultWeaponClasses = autoGenerateDefaultWeaponClasses;
	}

	/**
	 * Gets whether default weapons should be generated automatically.
	 */
	public boolean isAutoGenerateDefaultWeapons() {
		return autoGenerateDefaultWeapons;
	}

	/**
	 * Sets whether default weapons should be generated automatically.
	 */
	public void setAutoGenerateDefaultWeapons(boolean autoGenerateDefaultWeapons) {
		this.autoGenerateDefaultWeapons = autoGenerateDefaultWeapons;
	}

	/**
	 * Gets the default mystery box cost.
	 */
	public int getDefaultMysteryBoxCost() {
		return defaultMysteryBoxCost;
	}

	/**
	 * Sets the default mystery box cost.
	 */
	public void setDefaultMysteryBoxCost(int defaultMysteryBoxCost) {
		this.defaultMysteryBoxCost = defaultMysteryBoxCost;
	}

	/**
	 * Gets the world name.
	 */
	public String getWorldName() {
		return worldName;
	}

	/**
	 * Sets the world name.
	 */
	public void setWorldName(String worldName) {
		this.worldName = worldName;
	}
}